name: CadiaRanks
author: Hellgast23, Sam Taber
main: taber.ranks.CadiaRanks
version: 1.3
depend: [Vault]

commands:
    rankscore:
        usage: /rankscore <add|take|set|check|list>
        description: Add, take, set, get the score list, or check the score of the specified player.
        permission: taberranks.admin

permission:
    taberranks.admin:
        default: op
    taberranks.norankcheck:
        default: false